name: flutter_login
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  bloc_dev_tools:
    path: ../../packages/bloc_dev_tools

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
